# Generated by Django 4.0.3 on 2022-10-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='name',
        ),
        migrations.AddField(
            model_name='hat',
            name='color',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hat',
            name='fabric',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hat',
            name='picture_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hat',
            name='style_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
